spring.application.name=restTest00
server.port=8097

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/testdb
spring.datasource.username=green
spring.datasource.password=1234

# JWT
jwt.secret=sorkaksdlfgksmfdlfkausrmeodnlgoshfogkrpTdj
jwt.expiration=3600000

# mybatis
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml